### PR TITLE
Edit

### PR DESCRIPTION
**Pull request by EvalVis**
Now users can edit their business and read feedbacks privately.

### CODE REVIEW

**Review by Yar3k — APPROVED** [review]
Great work

**Review by Yar3k — CHANGES_REQUESTED** [review]
For some reason search dont work and pages too (404 error)

**Comment by Yar3k** [comment]
I noticed, everything, that is connected with id is not working like (links): "/Daužtas%20BMW/page1", 
"/page2/?os=&bi=&si=0&w=1111111&f=23:59:00&t=23:59:00"

**Comment by EvalVis** [comment]
I know this. Comment Razor pages in Startup.cs for now.

**Comment by EvalVis** [comment]
I will transfer this bug to issues and fix it later.

**Review by Yar3k — APPROVED** [review]
Well done

**Review by MartynaUb — APPROVED** [review]

**Pull request merged**
