### PR TITLE
Xamarin

### LINKED ISSUE #33: Duplicate emails
Clicking rapidly on client side could cause duplicate email entries to appear on database. Need a lock.

### PR DESCRIPTION
**Pull request by EvalVis**
Consuming REST API with Xamarin.

### CODE REVIEW

**Comment by EvalVis** [comment]
Bug resolved.

**Review by Yar3k — APPROVED** [review]
Well probably everything works. Rest api works, app works too, but sadly I could not run program fully. Probably app not consuming from rest api (well at least for me) :(

**Comment by EvalVis** [comment]
Should work now. Please check.

**Comment by EvalVis** [comment]
Although major, this bug was easy to fix. Tip of the day: you need to call even your code variables the same as DB Table name in Db context child class.

**Review by MartynaUb — APPROVED** [review]
Everything seems correct, good work

**Pull request merged**
