### PR TITLE
Add functionality to include pictures in advertisement

### PR DESCRIPTION
**Pull request by MartynaUb**

### CODE REVIEW

**Review by EvalVis — APPROVED** [review]
Fantastic. We are one step closer to advertising multiple products if we want to.

**Comment by EvalVis** [comment]
Just one tip. As said, If we want, we could advertise products with pictures. However, a business itself could have one separate picture (like in skelbiu.lt) which we could show on business board.

**Comment by MartynaUb** [comment]
> Just one tip. As said, If we want, we could advertise products with pictures. However, a business itself could have one separate picture (like in skelbiu.lt) which we could show on business board.

Good idea, will implement it next week

**Review by Yar3k — COMMENTED** [review]
Nice

**Review by Yar3k — APPROVED** [review]

**Pull request merged**
