### PR TITLE
Product

### PR DESCRIPTION
**Pull request by EvalVis**
Feature that allows to show several products, not just one.

### CODE REVIEW

**Comment by EvalVis** [comment]
About creating two tables for pictures. I thought about it, and maybe there is a better solution. We have products table, so maybe just add picture to products table and only one picture for business. Because I thought, who would want to photo a tiny counter multiple times. They would want to photo the products, one time each. I will commit my sugesstion. Please tell me what do you think.

**Comment by Yar3k** [comment]
> About creating two tables for pictures. I thought about it, and maybe there is a better solution. We have products table, so maybe just add picture to products table and only one picture for business. Because I thought, who would want to photo a tiny counter multiple times. They would want to photo the products, one time each. I will commit my sugesstion. Please tell me what do you think.

Great Idea

**Review by Yar3k — APPROVED** [review]
Nice job

**Comment by EvalVis** [comment]
New update please verify.

**Review by Yar3k — APPROVED** [review]
Good job

**Review by MartynaUb — APPROVED** [review]
Good solution, everything looks ok

**Pull request merged**
